spring.application.name=asc

spring.mongodb.uri=mongodb+srv://alexzsphone_db_user:apoSZ8tlRgsRaHEA@cluster0.r0r7x8m.mongodb.net/pedidos_cliente_db?appName=Cluster0

pedidos.url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/pedidos
items.url=https://6994a4eab081bc23e9c0f61e.mockapi.io/api/v1/items
